language: node_js
node_js:
- 0.12.7
sudo: false
cache:
  directories:
  - node_modules
before_install:
- npm prune
before_script:
- npm install --global gulp
script:
- gulp build-release
env:
  global:
  - secure: ir61HfofNejhK0KHqFEwSdkntWgn0sqxdhzGsfhue3aSKBXS3T/FBNS15rYPNtkTrh+wQgBCk02L0vvsLBBrL5DCBJP/pV9e6AsckDdW8Lc6pOlzsvAl84LOOMe845aCd9ZPl7iAqsx1WX/oueP3p0wsQui4NBOfkYgtBU4ltpYnjQZW+fyfOauxKg7scApBgsOGqi9qWZJwXOfW0euTvRY2bhNMv6ZcTq2AvQ5BJ/2bfQ2W14ziPPAQ7anog4jR917/er72irt/KVud2+6h9fPCeHJPWvG6+8JqmrfbRWqBnsccaCJYTGERHJ1M8Bg78S9j+eFXZZsMvX7LZ8uSs0u0CB4jV7lFQ8Sqt8cilT1zEVGV8kR1nHKbLnwV8QUz4Vjhnu7AgHKiX3zaQFrAWhtRCDJjfamDu+xiN3Qyqo20lT9gZ2Qxxb0aX+DlaIZjnbY3iMq9emwap1g+FBcLXCtjE6ovr0bA6HJu0Z2h1HXp7VhBWXQ5LNna/LkRdCr/ETmLP+G2wMvImeE0kUtVOeQ3DTWZOI1/g/OULWrVTT1S3emWAvvSDVq+QIEx+6NRvkEtnmb12oP89dnBabP1aF0TDDvt//WTkTQQCL4t0+A/R+omKhN2StxNJhbut4dnvY5gJp3eqRGtnDTvFDR0K58WceXmwmebRIk6g2HUMq4=
  - secure: f37bobSGAyvLHzALP2J5mYjzOKOEisBh+1xwrNkpJX7ZHWZEref5Njv2IrlnMurxaG1Ormn4t/B2v394BWeT+FuLJWCfMZ6Xo1RDBeacA7zmz71jUFLAIIkgM8tz3EDF7sf0wGCJY2UWXwvIq+1H3YQDCWLuTH1q3rdMFhjht8+X85u/f7obiUtUEdR6zxeQLBtFAkK54y4cZ8IIFUB1GUwkK73RHgJzqB5SMn1Mf6SYBeQM776SoDM0eRlyLxZYtRlFMf+ti5fFW+wIK7AbPrImO7anejcsAZoSU7qkKOOQQBjaYJmxjB1fqZwubMWLMWp6IsGd0BJzRcl9jbB7k0Y9hrJ27hz4ZaMxc+yiWUZv5F5eCiHBLesXKrorByb9qt3recPbreupGfp7MNHSWCtIHCdsHmfluF3VV2aH82K7+Zs15sMhz8/6pKV7YP0anK7q/tibhUhsqVRct2ceTuDsQW8Z9IJeSG9Lg7Jr1pvZHQVrsbiP7N5dXB27hgDz92Om6/bMgsgqYjQZ6dhf79fs/WU8/XIx/S2dCTl9ALKuCOGx0TTYJJJPvFrQD7YLay2CoGiET28pizAA/lte9Bk7C7xa75t03vh6Ea2gHTBbiAp2NI7L0RBG92u8/Lio+zvARrJ020g+Ut1f8cygZLxy2E/Mfm7i7juNwvEQeu4=
