language: node_js
node_js:
  - "0.12.7"
sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm prune
before_script:
  - npm install --global gulp

script:
  - gulp build-minify
